/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimatedWas: typeof import('./src/components/AnimatedWas.vue')['default']
    ButtonWas: typeof import('./src/components/ButtonWas.vue')['default']
    CursorLayer: typeof import('./src/components/CursorLayer.vue')['default']
    GameScene: typeof import('./src/components/GameScene.vue')['default']
    LoginScene: typeof import('./src/components/LoginScene.vue')['default']
    StaticWas: typeof import('./src/components/StaticWas.vue')['default']
    TipLayer: typeof import('./src/components/TipLayer.vue')['default']
  }
}
